<?php

namespace Acme\HelloBundle\Repository;

/**
 * ProduktRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduktRepository extends \Doctrine\ORM\EntityRepository
{
}
